import Head from 'next/head';
import Header from '../components/header';
import AllCoins from '../components/allCoins';

export default function Home() {
  return (
    <>
      <Head>
        <title>Trading App</title>
        <meta name='description' content='Generated by trading app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-gray-100 min-h-screen'>
        <Header />
        <AllCoins />
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          
        </div>
      </main>
    </>
  );
}
